name: R CMD check & build site

on:
  workflow_dispatch:
  push:
    paths:
      - 'DESCRIPTION'
      - '**.yml'
    branches:
      - devel
      - RELEASE_3_21

env:
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  CRAN: https://p3m.dev/cran/__linux__/noble/latest
  BIOC_RELEASE: RELEASE_3_21

jobs:
  set-matrix:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - name: Set Matrix Bioconductor Version
        id: set
        run: |
          MATRIX="{\"include\":[{\"bioc_version\":\"$GITHUB_REF_NAME\"}]}"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  check:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    container: bioconductor/bioconductor_docker:${{ matrix.bioc_version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.bioc_version }}

      - name: Query dependencies
        run: |
          BiocManager::install(c("covr", "BiocCheck"))
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ runner.os }}-r-${{ matrix.bioc_version }}-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.bioc_version }}-

      - name: Install GPG
        run: sudo apt-get update && sudo apt-get install -y gpg

      - name: Install Dependencies
        run: |
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())
          BiocManager::install(ask = FALSE, update = TRUE)
        shell: Rscript {0}

      - name: Check Package
        id: rcmdcheck
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "error", check_dir = "check")
        shell: Rscript {0}

      - name: Test coverage
        if: ${{ success() && github.ref == 'refs/heads/devel' }}
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            type = "all",
            install_path = file.path(
              normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"),
              "package"
            )
          )
          covr::to_cobertura(cov)
        shell: Rscript {0}

      - name: Upload test results to Codecov
        if: ${{ success() && github.ref == 'refs/heads/devel' }}
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: ${{ github.event_name != 'pull_request' && true || false }}
          file: ./cobertura.xml
          plugin: noop
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run BiocCheck
        id: bioccheck
        run: |
          BiocCheck::BiocCheck(
            dir('check', 'tar.gz$', full.names = TRUE),
            `quit-with-status` = TRUE, `no-check-bioc-help` = TRUE
          )
        shell: Rscript {0}

      - name: Build pkgdown
        if: github.ref == format('refs/heads/{0}', env.BIOC_RELEASE)
        run: |
           PATH=$PATH:$HOME/bin/ Rscript -e 'pkgdown::build_site()'

      - name: Upload pkgdown artifact
        if: github.ref == format('refs/heads/{0}', env.BIOC_RELEASE)
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: check
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        if: github.ref == format('refs/heads/{0}', env.BIOC_RELEASE)
        id: deployment
        uses: actions/deploy-pages@v4
